version: '3'
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    working_dir: /var/www
    networks:
      - app-network
    volumes:
      - .:/var/www
    ports:
      - "8000"
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    networks:
      - app-network
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
networks:
  app-network:
    driver: bridge
